### ISSUE TITLE
Ensure correct computation observed terciles

### ISSUE THREAD

**Issue by Tinkaa** [OCHA-DAP/pa-anticipatory-action#246]
We are using CHIRPS data to compute historically observed below average precipitation. 
This code was written some time ago, but never properly code reviewed. 
Since we are now using it more often, it would be good to have a second pair of eyes looking at it. 

The code can be found [here](https://github.com/OCHA-DAP/pa-anticipatory-action/blob/13f2f3da764b108df659ec3eb9e102a56ad60a5d/src/indicators/drought/chirps_rainfallobservations.py#L195) (line 195-258). 
The output is for example used for Chad [here](https://github.com/OCHA-DAP/pa-anticipatory-action/blob/f4aa628bc185dac6c3d39e388c621ce1ac89500f/analyses/tcd/notebooks/forecasts/tcd_seas_bavg_precip_observed.md)

In general it looks decent to me but why I want to double check is because 
1) in both bfa and tcd we see much more prevalence of below average in the 80's and 90's than in the last 20 years. Maybe precipitation patterns or technologies changed but want to be sure it is not us
2) We don't see great correspondence between years with bavg precipitation and reported drought years. I am not perse surprised about this, but better be sure before we make claims on that. 

As sanity checks I did simple things like making sure the occurence of below average is 1/3. I also manually compared a subset of the dates to the anomalies on [CHC's early warning explorer](https://chc-ewx2.chc.ucsb.edu/) but mainly for more recent dates.

**Comment by Tinkaa** [comment]
![afbeelding](https://user-images.githubusercontent.com/12556634/144046229-7f37517f-6dd8-4da2-95cd-50d7bac1be8e.png)
Actually the prevalance of bavg precipiation in the 80s might be correct, see e.g. this messy graph from [here](https://pubs.usgs.gov/fs/2012/3070/FS2012-3070.pdf)

**Comment by turnerm** [comment]
I've looked very carefully at [this method](https://github.com/OCHA-DAP/pa-anticipatory-action/blob/13f2f3da764b108df659ec3eb9e102a56ad60a5d/src/indicators/drought/chirps_rainfallobservations.py#L195) (worked through an example myself) and it all looks good to me. Some minor comments but I don't think they will have any effect on the results:
- for the quantile function:
  - it could be good to set `skipna = True`
  - instead of passing `0.33` I would pass `1/3` (more precise)
- when you set null values to -666, could that potentially be biasing the sample low? Should these be kept as N/A instead?

I'll check the notebook next

**Comment by Tinkaa** [comment]
Did I ever say before you are a genius? ;) Thanks a lot, that gives a lot more confidence! Working on implementing your excellent ideas, will get back to it later.

**Comment by Tinkaa** [comment]
This has been inspected by #250 with the conclusion that methodologically it is correct. 
Some code improvements have been implemented in #254
